wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1654600379
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      3:
      - 13
      - 15
      - 16
      4: 3.7.11
      5: 0.12.11
      6: 4.17.0
      8:
      - 5
dataset:
  desc: null
  value: ontonotes
encoder:
  desc: null
  value: bert-base-uncased
layer:
  desc: null
  value: last
masking:
  desc: null
  value: train
property:
  desc: null
  value: ner
